const base = import.meta.env.BASE_URL || "/";

export const carouselPaths = [
  `${base}assets/carousel1.webp`,
  `${base}assets/carousel2.webp`,
  `${base}assets/carousel3.webp`,
  `${base}assets/carousel4.webp`,
  `${base}assets/carousel5.webp`,
  `${base}assets/carousel6.webp`,
  `${base}assets/carousel7.webp`,
  `${base}assets/carousel8.webp`,
  `${base}assets/carousel9.webp`,
  `${base}assets/carousel10.webp`,
  `${base}assets/carousel11.webp`,
  `${base}assets/carousel12.webp`,
  `${base}assets/carousel13.webp`,
  `${base}assets/carousel14.webp`,
  `${base}assets/carousel15.webp`,
  `${base}assets/carousel16.webp`,
  `${base}assets/carousel17.webp`,
  `${base}assets/carousel18.webp`,
  `${base}assets/carousel19.webp`,
  `${base}assets/carousel20.webp`,
  `${base}assets/carousel21.webp`,
  `${base}assets/carousel22.webp`,
  `${base}assets/carousel23.webp`,
  `${base}assets/carousel24.webp`,
  `${base}assets/carousel25.webp`,
  `${base}assets/carousel26.webp`,
];
